workflows:
  android-workflow:
    name: Android Build
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    cache:
      cache_paths:
        - ~/.pub-cache       # Cache de pacotes Dart/Flutter
        - ~/.gradle/caches   # Cache global do Gradle
        - $CM_BUILD_DIR/android/.gradle # Cache do Gradle específico do projeto
        # Adicione outros caches se necessário, ex: $HOME/Library/Caches/CocoaPods
    scripts:
      # Removido o script de limpeza de cache
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Build Android
        script: |
          flutter build apk --release
          # Adicione a flag abaixo se ainda tiver problemas com validação de dependências
          # flutter build apk --release --android-skip-build-dependency-validation
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      
  ios-workflow:
    name: iOS Build
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    cache:
      cache_paths:
        - ~/.pub-cache       # Cache de pacotes Dart/Flutter
        - $CM_BUILD_DIR/ios/Pods # Cache do CocoaPods
        - $HOME/Library/Caches/CocoaPods # Cache global do CocoaPods
        # Adicione outros caches se necessário
    scripts:
      # Removido o script de limpeza de cache
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Build iOS
        script: |
          cd ios
          pod install --repo-update # Adicionado --repo-update para garantir atualização dos repositórios
          cd ..
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/Runner.app

