name: lamafiacla
description: 'Aplicativo LaMafia: Federação - Gerenciamento de clã tático'
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: # Deixar pub resolver a versão mais recente compatível
  # Firebase
  firebase_core: 
  firebase_auth: 
  cloud_firestore: 
  firebase_storage: 
  # Estado e armazenamento
  provider: 
  shared_preferences: 
  # Plugins essenciais
  flutter_plugin_android_lifecycle: # Já atualizado parcialmente, deixar pub resolver
  path_provider: 
  # UI e formatação
  intl: 
  flutter_svg: 
  # Mídia
  cached_network_image: 
  flutter_cache_manager: 
  # Plugin de áudio para reprodução dos arquivos de áudio
  audioplayers: 
  # Mapas
  flutter_map: 
  latlong2: 
  # Notificações
  flutter_local_notifications: 
  # Utilitários
  uuid: 
  permission_handler: 
  connectivity_plus: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: # Deixar pub resolver
  flutter_launcher_icons: # Deixar pub resolver

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images_png/1000216621.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images_png/1000216621.png"

flutter:
  uses-material-design: true
  
  assets:
    - assets/images_png/
    - assets/audio/
    
  fonts:
    - family: Gothic
      fonts:
        - asset: assets/fonts/gothic.ttf
    - family: Digital
      fonts:
        - asset: assets/fonts/digital.ttf

